version: "3"

services:
  client:
    container_name: portafolio
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "4321:8080"
    networks:
      - main

networks:
  main:
    driver: bridge
    external: true
