name: multiverseland
services:
  client:
    container_name: multiverseland
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3002:3001"
 
    networks:
      - cloudflared 

networks: 
  cloudflared:
    driver: bridge
    external: true
    