name: multiverseland_react
services:
  client_react:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3001:3001"
 
    networks:
      - cloudflared 

networks: 
  cloudflared:
    driver: bridge
    external: true
    